apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8tz.io/injected: "true"
    k8tz.io/timezone: Europe/Rome
  name: mypay4-batch-import-dovuti-operatori
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mypay4
      job: batch
      run: mypay4-batch-import-dovuti-operatori
  template:
    metadata:
      annotations:
        k8tz.io/injected: "true"
        k8tz.io/timezone: Europe/Rome
        kubectl.kubernetes.io/default-container: mypay4-batch-import-dovuti-operatori
      labels:
        app: mypay4
        job: batch
        run: mypay4-batch-import-dovuti-operatori
    spec:
      containers:
      - env:
        - name: FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
          value: mypay4_batch_import_dovuti_operatori.access
        - name: TZ
          value: Europe/Rome
        envFrom:
        - secretRef:
            name: e45-fluent-config-secret
        image: _REGISTRY_ENTE_/common/mypay4-fluentd:latest
        imagePullPolicy: Always
        name: fluentd-agent
        resources:
          limits:
            cpu: "0.5"
            memory: 1Gi
          requests:
            cpu: "0.1"
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/log/batch
          name: access-logs
        - mountPath: /fluentd/etc
          name: mypay4-batch-fluent-config
        - mountPath: /etc/localtime
          name: k8tz
          readOnly: true
          subPath: Europe/Rome
        - mountPath: /usr/share/zoneinfo
          name: k8tz
          readOnly: true
      - command:
        - /batch/bin/BatchImportDovutiOperatori_run.sh
        env:
        - name: TZ
          value: Europe/Rome
        envFrom:
        - secretRef:
            name: mypay4-user-creds-secret
        image: _REGISTRY_ENTE_/mypay4/mypay4-batch-import-dovuti-operatori:latest
        imagePullPolicy: Always
        name: mypay4-batch-import-dovuti-operatori
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: "0.1"
            memory: 100Mi
        volumeMounts:
        - mountPath: /E45
          name: conf
        - mountPath: /var/log/batch
          name: access-logs
        - mountPath: /conf/batchImportDovutiOperatori-properties_1.0.properties
          name: mypay4-batch-import-dovuti-operatori-configs
          subPath: batchImportDovutiOperatori-properties_1.0.properties
        - mountPath: /conf/batch-data.properties
          name: mypay4-batch-import-dovuti-operatori-configs
          subPath: batch-data.properties
        - mountPath: /conf/log4j-talend.xml
          name: mypay4-batch-import-dovuti-operatori-configs
          subPath: log4j-talend.xml
        - mountPath: /conf/flusso-dovuti-operatori-service.xml
          name: mypay4-batch-import-dovuti-operatori-configs
          subPath: flusso-dovuti-operatori-service.xml
        - mountPath: /conf/log4j.properties
          name: mypay4-batch-import-dovuti-operatori-configs
          subPath: log4j.properties
        - mountPath: /etc/localtime
          name: k8tz
          readOnly: true
          subPath: Europe/Rome
        - mountPath: /usr/share/zoneinfo
          name: k8tz
          readOnly: true
      imagePullSecrets:
      - name: registry-_ENTE_-secret
      volumes:
      - name: conf
        persistentVolumeClaim:
          claimName: mypay4-claim
      - configMap:
          name: mypay4-batch-import-dovuti-operatori-configs
        name: mypay4-batch-import-dovuti-operatori-configs
      - emptyDir: {}
        name: access-logs
      - configMap:
          name: mypay4-batch-fluent-config
        name: mypay4-batch-fluent-config
      - hostPath:
          path: /usr/share/zoneinfo
        name: k8tz
