/**
 *     MyPay - Payment portal of Regione Veneto.
 *     Copyright (C) 2022  Regione Veneto
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package it.regioneveneto.mygov.payment.mypay4.ws.util;

/**
 * @author Monaco
 *
 */
public interface FaultCodeConstants {

	String CODE_PAA_SYSTEM_ERROR = "PAA_SYSTEM_ERROR";
	String DESC_PAA_SYSTEM_ERROR = "PAA SYSTEM ERROR";

	String OTHER_ERROR = "OTHER_ERROR";

	String ESITO_KO = "KO";
	String ESITO_OK = "OK";

	/**
	 * ERRORE GENERICO
	 */
	String PAA_SYSTEM_ERROR = "PAA_SYSTEM_ERROR";

	String PAA_WAIT = "PAA_WAIT";

	String PAA_UNMANAGED = "PAA_UNMANAGED";

	String PAA_NOT_INVOKED = "PAA_NOT_INVOKED";

	String PPT_ESITO_SCONOSCIUTO = "PPT_ESITO_SCONOSCIUTO";

	/**
	 * Errore generico per PAA_INVIA_RT
	 */
	String PAA_RPT_SCONOSCIUTA = "PAA_RPT_SCONOSCIUTA";

	String PAA_RT_DUPLICATA = "PAA_RT_DUPLICATA";

	String PAA_RT_NON_VALIDA = "PAA_RT_NON_VALIDA";
	
	String PAA_RT_SCONOSCIUTA = "PAA_RT_SCONOSCIUTA";

	/**
	 * Errore generico per PAA_ATTIVA_RPT
	 */
	String PAA_ATTIVA_RPT_INTERMEDIARIO_SCONOSCIUTO = "INTERMEDIARIO_SCONOSCIUTO";

//	String PAA_ATTIVA_RPT_PSP_SCONOSCIUTO = "PSP_SCONOSCIUTO";

	String PAA_ATTIVA_RPT_DUPLICATA = "ATTIVA_RPT_DUPLICATA";

	/**
	 * Errore generico per PAA_VERIFICA_RPT
	 */
	String PAA_VERIFICA_RPT_INTERMEDIARIO_SCONOSCIUTO = "INTERMEDIARIO_SCONOSCIUTO";

//	String PAA_VERIFICA_RPT_PSP_SCONOSCIUTO = "PSP_SCONOSCIUTO";

	//FAULT CODES PER: "paaVerificaRPT"  e  "paaAttivaRPT"
	String PAA_SINTASSI_XSD_CODE = "PAA_SINTASSI_XSD";
	String PPA_SINTASSI_XSD_STRING = "Errore di sintassi XSD.";
	String PAA_SINTASSI_EXTRAXSD_CODE = "PAA_SINTASSI_EXTRAXSD";
	String PAA_SEMANTICA_CODE = "PAA_SEMANTICA";
	String PAA_SEMANTICA_STRING = "Errore semantico.";
	String PAA_FIRMA_INDISPONIBILE_CODE = "PAA_FIRMA_INDISPONIBILE";
	String PAA_FIRMA_INDISPONIBILE_STRING = "Impossibile firmare.";
	String PAA_ID_DOMINIO_ERRATO_CODE = "PAA_ID_DOMINIO_ERRATO";
	String PAA_ID_DOMINIO_ERRATO_STRING = "La PAA non corrisponde al Dominio indicato.";
	String PAA_ID_INTERMEDIARIO_ERRATO_CODE = "PAA_ID_INTERMEDIARIO_ERRATO";
	String PAA_ID_INTERMEDIARIO_ERRATO_STRING = "Identificativo intermediario non corrispondente.";
	String PAA_STAZIONE_INT_ERRATA_CODE = "PAA_STAZIONE_INT_ERRATA";
	String PAA_STAZIONE_INT_ERRATA_STRING = "Stazione intermediario non corrispondente.";
	String PAA_PAGAMENTO_SCONOSCIUTO_CODE = "PAA_PAGAMENTO_SCONOSCIUTO";
	String PAA_PAGAMENTO_SCONOSCIUTO_STRING = "Pagamento in attesa risulta sconosciuto all’Ente Creditore.";
	String PAA_PAGAMENTO_DUPLICATO_CODE = "PAA_PAGAMENTO_DUPLICATO";
	String PAA_PAGAMENTO_DUPLICATO_STRING = "Pagamento in attesa risulta concluso all’Ente Creditore.";
	String PAA_PAGAMENTO_IN_CORSO_CODE = "PAA_PAGAMENTO_IN_CORSO";
	String PAA_PAGAMENTO_IN_CORSO_STRING = "Pagamento in attesa risulta in corso all’Ente Creditore.";
	String PAA_PAGAMENTO_ANNULLATO_CODE = "PAA_PAGAMENTO_ANNULLATO";
	String PAA_PAGAMENTO_ANNULLATO_STRING = "Pagamento in attesa risulta annullato all’Ente Creditore.";
	String PAA_PAGAMENTO_SCADUTO_CODE = "PAA_PAGAMENTO_SCADUTO";
	String PAA_PAGAMENTO_SCADUTO_STRING = "Pagamento in attesa risulta scaduto all’Ente Creditore.";
	String PAA_PAGAMENTO_NON_INIZIATO_CODE = "PAA_PAGAMENTO_NON_INIZIATO";
	String PAA_DOVUTO_NON_PAGABILE = "PAA_DOVUTO_NON_PAGABILE";
	String PAA_TIPO_VERSAMENTO_ERRATO = "PAA_TIPO_VERSAMENTO_ERRATO";
	String PAA_TIPO_DOVUTO_NON_VALIDO_PER_ENTE = "PAA_TIPO_DOVUTO_NON_VALIDO_PER_ENTE";
	String PAA_TIPO_DOVUTO_NON_ABILITATO_PER_ENTE = "PAA_TIPO_DOVUTO_NON_ABILITATO_PER_ENTE";
	String PAA_ATTIVA_RPT_IMPORTO_NON_VALIDO = "PAA_ATTIVA_RPT_IMPORTO_NON_VALIDO";
	String PAA_ERROR_CATALOGO_INFORMATIVO = "PAA_ERROR_CATALOGO_INFORMATIVO";
	String PAA_CATALOGO_INFORMATIVO_NESSUN_PSP = "PAA_CATALOGO_INFORMATIVO_NESSUN_PSP";


	String PAA_ENTE_NON_VALIDO_CODE = "PAA_ENTE_NON_VALIDO";
	String PAA_LIMITAZIONE_ENTI_SECONDARI_ERROR = "PAA_LIMITAZIONE_ENTI_SECONDARI_ERROR";
	String PAA_XML_NON_VALIDO_CODE = "PAA_XML_NON_VALIDO";
	String PAA_AZIONE_NON_VALIDO_CODE = "PAA_AZIONE_NON_VALIDO";
	String PAA_IUV_NON_VALIDO_CODE = "PAA_IUV_NON_VALIDO";
	String PAA_IUV_NON_VALIDO_STRING = "IUV non valido.";
	String PAA_IMPORTO_SINGOLO_VERSAMENTO_NON_VALIDO_CODE = "PAA_IMPORTO_SINGOLO_VERSAMENTO_NON_VALIDO";
	String PAA_IMPORTO_BILANCIO_NON_VALIDO_CODE = "PAA_IMPORTO_BILANCIO_NON_VALIDO";
	String PAA_IDENTIFICATIVO_TIPO_DOVUTO_NON_VALIDO_CODE = "PAA_IDENTIFICATIVO_TIPO_DOVUTO_NON_VALIDO";
	String PAA_IDENTIFICATIVO_TIPO_DOVUTO_NON_ABILITATO_CODE = "PAA_IDENTIFICATIVO_TIPO_DOVUTO_NON_ABILITATO";
	String PAA_SOGG_PAG_NON_VALORIZZATO_CODE = "PAA_SOGG_PAG_NON_VALORIZZATO";
	String PAA_TIPO_VERSAMENTO_NON_VALIDO_CODE = "PAA_TIPO_VERSAMENTO_NON_VALIDO";
	String PAA_IUD_NON_VALIDO_CODE = "PAA_IUD_NON_VALIDO";
	String PAA_IDENT_TIPO_DOVUTO_NON_PRESENTE_CODE = "PAA_IDENT_TIPO_DOVUTO_NON_PRESENTE";
	String PAA_CAUSALE_NON_PRESENTE_CODE = "PAA_CAUSALE_NON_PRESENTE";
	String PAA_DATI_SPECIFICI_RISCOSSIONE_NON_VALIDO_CODE = "PAA_DATI_SPECIFICI_RISCOSSIONE_NON_VALIDO";
	String PAA_CODICE_FISCALE_NON_VALIDO_CODE = "PAA_CODICE_FISCALE_NON_VALIDO";
	String PAA_P_IVA_NON_VALIDO_CODE = "PAA_P_IVA_NON_VALIDO";




	String PPT_IBAN_NON_CENSITO_CODE = "PPT_IBAN_NON_CENSITO";


	/**
	 * ERRORI PER VERIFICA FIRMA
	 */
	String PAA_TIPOFIRMA_SCONOSCIUTO = "PAA_TIPOFIRMA_SCONOSCIUTO";

	String PAA_ERRORE_FORMATO_BUSTA_FIRMATA = "PAA_ERRORE_FORMATO_BUSTA_FIRMATA";

	String PAA_FIRMA_ERRATA = "PAA_FIRMA_ERRATA";

	/**
	 *  ERRORI WISP
	 */
	String PAA_CHIEDI_SCELTA_WISP = "PAA_CHIEDI_SCELTA_WISP";
	String PAA_PSP_NON_TROVATO = "PAA_PSP_NON_TROVATO";

	/**
	 *  Errori chiedi copia esito
	 */
	String PAA_CHIEDI_COPIA_ESITO_ENTE_NON_PRESENTE = "PAA_CHIEDI_COPIA_ESITO_ENTE_NON_PRESENTE";

	String PAA_CHIEDI_COPIA_ESITO_ERRORE = "PAA_CHIEDI_COPIA_ESITO_ERRORE";

	String PAA_RPT_NON_PRESENTE = "PAA_RPT_NON_PRESENTE";
	
	String PAA_RT_NON_PRESENTE = "PAA_RT_NON_PRESENTE";

	String PAA_RT_GIA_PRESENTE = "PAA_RT_GIA_PRESENTE";
	
	/**
	 *  ERRORI PER AVVISI DIGITALI
	 */
	String PAA_NODO_INVIA_AVVISO_DIGITALE = "PAA_NODO_INVIA_AVVISO_DIGITALE";
	String PAA_NODO_SIL_INVIA_AVVISO_DIGITALE = "PAA_NODO_SIL_INVIA_AVVISO_DIGITALE";

	
	/**
	 * ERRORI paaChiediNumeroAvviso
	 */
	String PAA_ID_INTERMEDIARIO_ERRATO = "PAA_ID_INTERMEDIARIO_ERRATO";
	String PAA_STAZIONE_INT_ERRATA = "PAA_STAZIONE_INT_ERRATA";
	String PAA_ID_DOMINIO_ERRATO = "PAA_ID_DOMINIO_ERRATO";
	
	/**
	 * ERRORI XML
	 */
	String PAA_SINTASSI_EXTRAXSD = "PAA_SINTASSI_EXTRAXSD";
	String PAA_SINTASSI_XSD = "PAA_SINTASSI_XSD";
	String PAA_SEMANTICA = "PAA_SEMANTICA";
	
	/**
	 * ERRORI paaInviaRichiestaRevoca
	 */
	String PAA_ER_DUPLICATA = "PAA_ER_DUPLICATA";

	/**
	 * ERRORI PagamentiTelematiciDovutiPagatiImpl
	 */
	String CODE_PAA_ENTE_NON_VALIDO = "PAA_ENTE_NON_VALIDO";
	String CODE_PAA_IDENTIFICATIVO_TIPO_DOVUTO_NON_INSERITO = "PAA_IDENTIFICATIVO_TIPO_DOVUTO_NON_INSERITO";
	String CODE_PAA_STATO_ENTE_NON_VALIDO = "PAA_STATO_ENTE_NON_VALIDO";
	String CODE_PAA_TIPO_VERSAMENTO_NON_VALIDO = "PAA_TIPO_VERSAMENTO_NON_VALIDO";
	String CODE_PAA_IUD_NON_VALIDO = "PAA_IUD_NON_VALIDO";
	String CODE_PAA_DATI_SPECIFICI_RISCOSSIONE_NON_VALIDO = "PAA_DATI_SPECIFICI_RISCOSSIONE_NON_VALIDO";
	String CODE_PAA_CODICE_FISCALE_NON_VALIDO = "PAA_CODICE_FISCALE_NON_VALIDO";
	String CODE_PAA_P_IVA_NON_VALIDO = "PAA_P_IVA_NON_VALIDO";
	String CODE_PAA_REQUEST_TOKEN_NON_VALIDO = "PAA_REQUEST_TOKEN_NON_VALIDO";
	String CODE_PAA_DATI_NON_TROVATI = "PAA_DATI_NON_TROVATI";
	String CODE_PAA_DATE_FROM_NON_VALIDO = "PAA_DATE_FROM_NON_VALIDO";
	String CODE_PAA_DATE_TO_NON_VALIDO = "PAA_DATE_TO_NON_VALIDO";
	String CODE_PAA_INTERVALLO_DATE_NON_VALIDO = "PAA_INTERVALLO_DATE_NON_VALIDO";
	String CODE_PAA_IDENTIFICATIVO_TIPO_DOVUTO_NON_VALIDO = "PAA_IDENTIFICATIVO_TIPO_DOVUTO_NON_VALIDO";
	String CODE_PAA_IDENTIFICATIVO_TIPO_DOVUTO_NON_ABILITATO = "PAA_IDENTIFICATIVO_TIPO_DOVUTO_NON_ABILITATO";
	String CODE_PAA_XML_NON_VALIDO = "PAA_XML_NON_VALIDO";
	String CODE_PAA_IUD_DUPLICATO = "PAA_IUD_DUPLICATO";
	String CODE_PAA_IUV_DUPLICATO = "PAA_IUV_DUPLICATO";
	String CODE_PAA_IUV_NON_VALIDO = "PAA_IUV_NON_VALIDO";
	String CODE_PAA_NUMERO_DOVUTI_PER_IUV_NON_VALIDO = "PAA_NUMERO_DOVUTI_PER_IUV_NON_VALIDO";
	String CODE_PAA_IUV_SCADUTO = "PAA_IUV_SCADUTO";
	String CODE_PAA_ID_SESSION_NON_VALIDO = "PAA_ID_SESSION_NON_VALIDO";
	String CODE_PAA_PAGAMENTO_NON_INIZIATO = "PAA_PAGAMENTO_NON_INIZIATO";
	String CODE_PAA_PAGAMENTO_IN_CORSO = "PAA_PAGAMENTO_IN_CORSO";
	String CODE_PAA_PAGAMENTO_ANNULLATO = "PAA_PAGAMENTO_ANNULLATO";
	String CODE_PAA_PAGAMENTO_SCADUTO = "PAA_PAGAMENTO_SCADUTO";
	String WS_USER = "WS_USER";
	String CODE_PAA_TIPO_IDENTIFICATIVO_PAGATORE_NON_VALIDO = "PAA_TIPO_IDENTIFICATIVO_PAGATORE_NON_VALIDO";
	String CODE_PAA_CODICE_IDENTIFICATIVO_PAGATORE_NON_PRESENTE = "PAA_CODICE_IDENTIFICATIVO_PAGATORE_NON_PRESENTE";
	String CODE_PAA_VERSIONE_TRACCIATO_NON_VALIDA = "PAA_VERSIONE_TRACCIATO_NON_VALIDA";
	String CODE_PAA_SERVIZIO_NON_IMPLEMENTATO = "PAA_SERVIZIO_NON_IMPLEMENTATO";
	String CODE_PAA_IMPORTO_MARCA_BOLLO_DIGITALE_NON_VALIDA = "PAA_IMPORTO_MARCA_BOLLO_DIGITALE_NON_VALIDA";
	String CODE_PAA_MARCA_BOLLO_DIGITALE_NON_VALIDA = "PAA_MARCA_BOLLO_DIGITALE_NON_VALIDA";
	String CODE_PAA_IMPORTO_BILANCIO_NON_VALIDO = "PAA_IMPORTO_BILANCIO_NON_VALIDO";
	String CODE_PAA_LIMITE_MASSIMO_DOVUTI_ENTI_SECONDARI = "PAA_LIMITE_MASSIMO_DOVUTI_ENTI_SECONDARI";
	String CODE_PAA_IMPORTO_SINGOLO_VERSAMENTO_NON_VALIDO = "PAA_IMPORTO_SINGOLO_VERSAMENTO_NON_VALIDO";
	String CODE_PAA_ANAGRAFICA_NON_VALIDA = "PAA_ANAGRAFICA_NON_VALIDA";
	String CODE_PAA_ERRORE_RECUPERO_DOVUTI_ENTI_SECONDARI = "PAA_ERRORE_RECUPERO_DOVUTI_ENTI_SECONDARI";
	String CODE_PAA_LIMITE_MASSIMO_DOVUTI_MULTIBENEFICIARI = "PAA_LIMITE_MASSIMO_DOVUTI_MULTIBENEFICIARI";
	String CODE_PAA_ENTE_SECONDARIO_NON_VALIDO = "PAA_ENTE_SECONDARIO_NON_VALIDO";
}