package it.regioneveneto.mygov.payment.nodoregionalefesp.domain;
// Generated Jul 14, 2017 12:18:12 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * MygovRpEDettaglio generated by hbm2java
 */
public class MygovRpEDettaglio implements java.io.Serializable {

	private Long mygovRpEDettaglioId;

	private int version;

	private MygovRpE mygov_rp_e;

	private Date dtCreazione;

	private Date dtUltimaModifica;

	private BigDecimal numRpDatiVersDatiSingVersImportoSingoloVersamento;

	private BigDecimal numRpDatiVersDatiSingVersCommissioneCaricoPa;

	private String codRpDatiVersDatiSingVersIbanAccredito;

	private String codRpDatiVersDatiSingVersBicAccredito;

	private String codRpDatiVersDatiSingVersIbanAppoggio;

	private String codRpDatiVersDatiSingVersBicAppoggio;

	private String codRpDatiVersDatiSingVersCredenzialiPagatore;

	private String deRpDatiVersDatiSingVersCausaleVersamento;

	private String deRpDatiVersDatiSingVersDatiSpecificiRiscossione;

	private BigDecimal numEDatiPagDatiSingPagSingoloImportoPagato;

	private String deEDatiPagDatiSingPagEsitoSingoloPagamento;

	private Date dtEDatiPagDatiSingPagDataEsitoSingoloPagamento;

	private String codEDatiPagDatiSingPagIdUnivocoRiscoss;

	private String deEDatiPagDatiSingPagCausaleVersamento;

	private String deEDatiPagDatiSingPagDatiSpecificiRiscossione;

	private BigDecimal numEDatiPagDatiSingPagCommissioniApplicatePsp;

	private String codEDatiPagDatiSingPagAllegatoRicevutaTipo;

	private byte[] blbEDatiPagDatiSingPagAllegatoRicevutaTest;

	private String codRpDatiVersDatiSingVersDatiMbdTipoBollo;

	private String codRpDatiVersDatiSingVersDatiMbdHashDocumento;

	private String codRpDatiVersDatiSingVersDatiMbdProvinciaResidenza;

	public MygovRpEDettaglio() {
	}

	public MygovRpEDettaglio(MygovRpE mygov_rp_e, Date dtCreazione, Date dtUltimaModifica, BigDecimal numRpDatiVersDatiSingVersImportoSingoloVersamento,
			String deRpDatiVersDatiSingVersCausaleVersamento, String deRpDatiVersDatiSingVersDatiSpecificiRiscossione) {
		this.mygov_rp_e = mygov_rp_e;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.numRpDatiVersDatiSingVersImportoSingoloVersamento = numRpDatiVersDatiSingVersImportoSingoloVersamento;
		this.deRpDatiVersDatiSingVersCausaleVersamento = deRpDatiVersDatiSingVersCausaleVersamento;
		this.deRpDatiVersDatiSingVersDatiSpecificiRiscossione = deRpDatiVersDatiSingVersDatiSpecificiRiscossione;
	}

	public MygovRpEDettaglio(MygovRpE mygov_rp_e, Date dtCreazione, Date dtUltimaModifica, BigDecimal numRpDatiVersDatiSingVersImportoSingoloVersamento,
			BigDecimal numRpDatiVersDatiSingVersCommissioneCaricoPa, String codRpDatiVersDatiSingVersIbanAccredito,
			String codRpDatiVersDatiSingVersBicAccredito, String codRpDatiVersDatiSingVersIbanAppoggio, String codRpDatiVersDatiSingVersBicAppoggio,
			String codRpDatiVersDatiSingVersCredenzialiPagatore, String deRpDatiVersDatiSingVersCausaleVersamento,
			String deRpDatiVersDatiSingVersDatiSpecificiRiscossione, BigDecimal numEDatiPagDatiSingPagSingoloImportoPagato,
			String deEDatiPagDatiSingPagEsitoSingoloPagamento, Date dtEDatiPagDatiSingPagDataEsitoSingoloPagamento,
			String codEDatiPagDatiSingPagIdUnivocoRiscoss, String deEDatiPagDatiSingPagCausaleVersamento, String deEDatiPagDatiSingPagDatiSpecificiRiscossione,
			BigDecimal numEDatiPagDatiSingPagCommissioniApplicatePsp, String codEDatiPagDatiSingPagAllegatoRicevutaTipo,
			byte[] blbEDatiPagDatiSingPagAllegatoRicevutaTest, String codRpDatiVersDatiSingVersDatiMbdTipoBollo,
			String codRpDatiVersDatiSingVersDatiMbdHashDocumento, String codRpDatiVersDatiSingVersDatiMbdProvinciaResidenza) {
		this.mygov_rp_e = mygov_rp_e;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.numRpDatiVersDatiSingVersImportoSingoloVersamento = numRpDatiVersDatiSingVersImportoSingoloVersamento;
		this.numRpDatiVersDatiSingVersCommissioneCaricoPa = numRpDatiVersDatiSingVersCommissioneCaricoPa;
		this.codRpDatiVersDatiSingVersIbanAccredito = codRpDatiVersDatiSingVersIbanAccredito;
		this.codRpDatiVersDatiSingVersBicAccredito = codRpDatiVersDatiSingVersBicAccredito;
		this.codRpDatiVersDatiSingVersIbanAppoggio = codRpDatiVersDatiSingVersIbanAppoggio;
		this.codRpDatiVersDatiSingVersBicAppoggio = codRpDatiVersDatiSingVersBicAppoggio;
		this.codRpDatiVersDatiSingVersCredenzialiPagatore = codRpDatiVersDatiSingVersCredenzialiPagatore;
		this.deRpDatiVersDatiSingVersCausaleVersamento = deRpDatiVersDatiSingVersCausaleVersamento;
		this.deRpDatiVersDatiSingVersDatiSpecificiRiscossione = deRpDatiVersDatiSingVersDatiSpecificiRiscossione;
		this.numEDatiPagDatiSingPagSingoloImportoPagato = numEDatiPagDatiSingPagSingoloImportoPagato;
		this.deEDatiPagDatiSingPagEsitoSingoloPagamento = deEDatiPagDatiSingPagEsitoSingoloPagamento;
		this.dtEDatiPagDatiSingPagDataEsitoSingoloPagamento = dtEDatiPagDatiSingPagDataEsitoSingoloPagamento;
		this.codEDatiPagDatiSingPagIdUnivocoRiscoss = codEDatiPagDatiSingPagIdUnivocoRiscoss;
		this.deEDatiPagDatiSingPagCausaleVersamento = deEDatiPagDatiSingPagCausaleVersamento;
		this.deEDatiPagDatiSingPagDatiSpecificiRiscossione = deEDatiPagDatiSingPagDatiSpecificiRiscossione;
		this.numEDatiPagDatiSingPagCommissioniApplicatePsp = numEDatiPagDatiSingPagCommissioniApplicatePsp;
		this.codEDatiPagDatiSingPagAllegatoRicevutaTipo = codEDatiPagDatiSingPagAllegatoRicevutaTipo;
		this.blbEDatiPagDatiSingPagAllegatoRicevutaTest = blbEDatiPagDatiSingPagAllegatoRicevutaTest;
		this.codRpDatiVersDatiSingVersDatiMbdTipoBollo = codRpDatiVersDatiSingVersDatiMbdTipoBollo;
		this.codRpDatiVersDatiSingVersDatiMbdHashDocumento = codRpDatiVersDatiSingVersDatiMbdHashDocumento;
		this.codRpDatiVersDatiSingVersDatiMbdProvinciaResidenza = codRpDatiVersDatiSingVersDatiMbdProvinciaResidenza;
	}

	public Long getMygovRpEDettaglioId() {
		return this.mygovRpEDettaglioId;
	}

	public void setMygovRpEDettaglioId(Long mygovRpEDettaglioId) {
		this.mygovRpEDettaglioId = mygovRpEDettaglioId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public MygovRpE getMygov_rp_e() {
		return this.mygov_rp_e;
	}

	public void setMygov_rp_e(MygovRpE mygov_rp_e) {
		this.mygov_rp_e = mygov_rp_e;
	}

	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

	public BigDecimal getNumRpDatiVersDatiSingVersImportoSingoloVersamento() {
		return this.numRpDatiVersDatiSingVersImportoSingoloVersamento;
	}

	public void setNumRpDatiVersDatiSingVersImportoSingoloVersamento(BigDecimal numRpDatiVersDatiSingVersImportoSingoloVersamento) {
		this.numRpDatiVersDatiSingVersImportoSingoloVersamento = numRpDatiVersDatiSingVersImportoSingoloVersamento;
	}

	public BigDecimal getNumRpDatiVersDatiSingVersCommissioneCaricoPa() {
		return this.numRpDatiVersDatiSingVersCommissioneCaricoPa;
	}

	public void setNumRpDatiVersDatiSingVersCommissioneCaricoPa(BigDecimal numRpDatiVersDatiSingVersCommissioneCaricoPa) {
		this.numRpDatiVersDatiSingVersCommissioneCaricoPa = numRpDatiVersDatiSingVersCommissioneCaricoPa;
	}

	public String getCodRpDatiVersDatiSingVersIbanAccredito() {
		return this.codRpDatiVersDatiSingVersIbanAccredito;
	}

	public void setCodRpDatiVersDatiSingVersIbanAccredito(String codRpDatiVersDatiSingVersIbanAccredito) {
		this.codRpDatiVersDatiSingVersIbanAccredito = codRpDatiVersDatiSingVersIbanAccredito;
	}

	public String getCodRpDatiVersDatiSingVersBicAccredito() {
		return this.codRpDatiVersDatiSingVersBicAccredito;
	}

	public void setCodRpDatiVersDatiSingVersBicAccredito(String codRpDatiVersDatiSingVersBicAccredito) {
		this.codRpDatiVersDatiSingVersBicAccredito = codRpDatiVersDatiSingVersBicAccredito;
	}

	public String getCodRpDatiVersDatiSingVersIbanAppoggio() {
		return this.codRpDatiVersDatiSingVersIbanAppoggio;
	}

	public void setCodRpDatiVersDatiSingVersIbanAppoggio(String codRpDatiVersDatiSingVersIbanAppoggio) {
		this.codRpDatiVersDatiSingVersIbanAppoggio = codRpDatiVersDatiSingVersIbanAppoggio;
	}

	public String getCodRpDatiVersDatiSingVersBicAppoggio() {
		return this.codRpDatiVersDatiSingVersBicAppoggio;
	}

	public void setCodRpDatiVersDatiSingVersBicAppoggio(String codRpDatiVersDatiSingVersBicAppoggio) {
		this.codRpDatiVersDatiSingVersBicAppoggio = codRpDatiVersDatiSingVersBicAppoggio;
	}

	public String getCodRpDatiVersDatiSingVersCredenzialiPagatore() {
		return this.codRpDatiVersDatiSingVersCredenzialiPagatore;
	}

	public void setCodRpDatiVersDatiSingVersCredenzialiPagatore(String codRpDatiVersDatiSingVersCredenzialiPagatore) {
		this.codRpDatiVersDatiSingVersCredenzialiPagatore = codRpDatiVersDatiSingVersCredenzialiPagatore;
	}

	public String getDeRpDatiVersDatiSingVersCausaleVersamento() {
		return this.deRpDatiVersDatiSingVersCausaleVersamento;
	}

	public void setDeRpDatiVersDatiSingVersCausaleVersamento(String deRpDatiVersDatiSingVersCausaleVersamento) {
		this.deRpDatiVersDatiSingVersCausaleVersamento = deRpDatiVersDatiSingVersCausaleVersamento;
	}

	public String getDeRpDatiVersDatiSingVersDatiSpecificiRiscossione() {
		return this.deRpDatiVersDatiSingVersDatiSpecificiRiscossione;
	}

	public void setDeRpDatiVersDatiSingVersDatiSpecificiRiscossione(String deRpDatiVersDatiSingVersDatiSpecificiRiscossione) {
		this.deRpDatiVersDatiSingVersDatiSpecificiRiscossione = deRpDatiVersDatiSingVersDatiSpecificiRiscossione;
	}

	public BigDecimal getNumEDatiPagDatiSingPagSingoloImportoPagato() {
		return this.numEDatiPagDatiSingPagSingoloImportoPagato;
	}

	public void setNumEDatiPagDatiSingPagSingoloImportoPagato(BigDecimal numEDatiPagDatiSingPagSingoloImportoPagato) {
		this.numEDatiPagDatiSingPagSingoloImportoPagato = numEDatiPagDatiSingPagSingoloImportoPagato;
	}

	public String getDeEDatiPagDatiSingPagEsitoSingoloPagamento() {
		return this.deEDatiPagDatiSingPagEsitoSingoloPagamento;
	}

	public void setDeEDatiPagDatiSingPagEsitoSingoloPagamento(String deEDatiPagDatiSingPagEsitoSingoloPagamento) {
		this.deEDatiPagDatiSingPagEsitoSingoloPagamento = deEDatiPagDatiSingPagEsitoSingoloPagamento;
	}

	public Date getDtEDatiPagDatiSingPagDataEsitoSingoloPagamento() {
		return this.dtEDatiPagDatiSingPagDataEsitoSingoloPagamento;
	}

	public void setDtEDatiPagDatiSingPagDataEsitoSingoloPagamento(Date dtEDatiPagDatiSingPagDataEsitoSingoloPagamento) {
		this.dtEDatiPagDatiSingPagDataEsitoSingoloPagamento = dtEDatiPagDatiSingPagDataEsitoSingoloPagamento;
	}

	public String getCodEDatiPagDatiSingPagIdUnivocoRiscoss() {
		return this.codEDatiPagDatiSingPagIdUnivocoRiscoss;
	}

	public void setCodEDatiPagDatiSingPagIdUnivocoRiscoss(String codEDatiPagDatiSingPagIdUnivocoRiscoss) {
		this.codEDatiPagDatiSingPagIdUnivocoRiscoss = codEDatiPagDatiSingPagIdUnivocoRiscoss;
	}

	public String getDeEDatiPagDatiSingPagCausaleVersamento() {
		return this.deEDatiPagDatiSingPagCausaleVersamento;
	}

	public void setDeEDatiPagDatiSingPagCausaleVersamento(String deEDatiPagDatiSingPagCausaleVersamento) {
		this.deEDatiPagDatiSingPagCausaleVersamento = deEDatiPagDatiSingPagCausaleVersamento;
	}

	public String getDeEDatiPagDatiSingPagDatiSpecificiRiscossione() {
		return this.deEDatiPagDatiSingPagDatiSpecificiRiscossione;
	}

	public void setDeEDatiPagDatiSingPagDatiSpecificiRiscossione(String deEDatiPagDatiSingPagDatiSpecificiRiscossione) {
		this.deEDatiPagDatiSingPagDatiSpecificiRiscossione = deEDatiPagDatiSingPagDatiSpecificiRiscossione;
	}

	public BigDecimal getNumEDatiPagDatiSingPagCommissioniApplicatePsp() {
		return this.numEDatiPagDatiSingPagCommissioniApplicatePsp;
	}

	public void setNumEDatiPagDatiSingPagCommissioniApplicatePsp(BigDecimal numEDatiPagDatiSingPagCommissioniApplicatePsp) {
		this.numEDatiPagDatiSingPagCommissioniApplicatePsp = numEDatiPagDatiSingPagCommissioniApplicatePsp;
	}

	public String getCodEDatiPagDatiSingPagAllegatoRicevutaTipo() {
		return this.codEDatiPagDatiSingPagAllegatoRicevutaTipo;
	}

	public void setCodEDatiPagDatiSingPagAllegatoRicevutaTipo(String codEDatiPagDatiSingPagAllegatoRicevutaTipo) {
		this.codEDatiPagDatiSingPagAllegatoRicevutaTipo = codEDatiPagDatiSingPagAllegatoRicevutaTipo;
	}

	public byte[] getBlbEDatiPagDatiSingPagAllegatoRicevutaTest() {
		return this.blbEDatiPagDatiSingPagAllegatoRicevutaTest;
	}

	public void setBlbEDatiPagDatiSingPagAllegatoRicevutaTest(byte[] blbEDatiPagDatiSingPagAllegatoRicevutaTest) {
		this.blbEDatiPagDatiSingPagAllegatoRicevutaTest = blbEDatiPagDatiSingPagAllegatoRicevutaTest;
	}

	public String getCodRpDatiVersDatiSingVersDatiMbdTipoBollo() {
		return this.codRpDatiVersDatiSingVersDatiMbdTipoBollo;
	}

	public void setCodRpDatiVersDatiSingVersDatiMbdTipoBollo(String codRpDatiVersDatiSingVersDatiMbdTipoBollo) {
		this.codRpDatiVersDatiSingVersDatiMbdTipoBollo = codRpDatiVersDatiSingVersDatiMbdTipoBollo;
	}

	public String getCodRpDatiVersDatiSingVersDatiMbdHashDocumento() {
		return this.codRpDatiVersDatiSingVersDatiMbdHashDocumento;
	}

	public void setCodRpDatiVersDatiSingVersDatiMbdHashDocumento(String codRpDatiVersDatiSingVersDatiMbdHashDocumento) {
		this.codRpDatiVersDatiSingVersDatiMbdHashDocumento = codRpDatiVersDatiSingVersDatiMbdHashDocumento;
	}

	public String getCodRpDatiVersDatiSingVersDatiMbdProvinciaResidenza() {
		return this.codRpDatiVersDatiSingVersDatiMbdProvinciaResidenza;
	}

	public void setCodRpDatiVersDatiSingVersDatiMbdProvinciaResidenza(String codRpDatiVersDatiSingVersDatiMbdProvinciaResidenza) {
		this.codRpDatiVersDatiSingVersDatiMbdProvinciaResidenza = codRpDatiVersDatiSingVersDatiMbdProvinciaResidenza;
	}

}
