package it.regioneveneto.mygov.payment.nodoregionalefesp.domain;
// Generated Jul 14, 2017 12:18:12 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * MygovGiornale generated by hbm2java
 */
public class MygovGiornale implements java.io.Serializable {

	private Long mygovGiornaleId;

	private int version;

	private Date dataOraEvento;

	private String identificativoDominio;

	private String identificativoUnivocoVersamento;

	private String codiceContestoPagamento;

	private String identificativoPrestatoreServiziPagamento;

	private String tipoVersamento;

	private String componente;

	private String categoriaEvento;

	private String tipoEvento;

	private String sottoTipoEvento;

	private String identificativoFruitore;

	private String identificativoErogatore;

	private String identificativoStazioneIntermediarioPa;

	private String canalePagamento;

	private String parametriSpecificiInterfaccia;

	private String esito;

	public MygovGiornale() {
	}

	public MygovGiornale(Date dataOraEvento, String identificativoDominio, String identificativoUnivocoVersamento, String codiceContestoPagamento,
			String identificativoPrestatoreServiziPagamento, String componente, String categoriaEvento, String tipoEvento, String sottoTipoEvento,
			String identificativoFruitore, String identificativoErogatore) {
		this.dataOraEvento = dataOraEvento;
		this.identificativoDominio = identificativoDominio;
		this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
		this.codiceContestoPagamento = codiceContestoPagamento;
		this.identificativoPrestatoreServiziPagamento = identificativoPrestatoreServiziPagamento;
		this.componente = componente;
		this.categoriaEvento = categoriaEvento;
		this.tipoEvento = tipoEvento;
		this.sottoTipoEvento = sottoTipoEvento;
		this.identificativoFruitore = identificativoFruitore;
		this.identificativoErogatore = identificativoErogatore;
	}

	public MygovGiornale(Date dataOraEvento, String identificativoDominio, String identificativoUnivocoVersamento, String codiceContestoPagamento,
			String identificativoPrestatoreServiziPagamento, String tipoVersamento, String componente, String categoriaEvento, String tipoEvento,
			String sottoTipoEvento, String identificativoFruitore, String identificativoErogatore, String identificativoStazioneIntermediarioPa,
			String canalePagamento, String parametriSpecificiInterfaccia, String esito) {
		this.dataOraEvento = dataOraEvento;
		this.identificativoDominio = identificativoDominio;
		this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
		this.codiceContestoPagamento = codiceContestoPagamento;
		this.identificativoPrestatoreServiziPagamento = identificativoPrestatoreServiziPagamento;
		this.tipoVersamento = tipoVersamento;
		this.componente = componente;
		this.categoriaEvento = categoriaEvento;
		this.tipoEvento = tipoEvento;
		this.sottoTipoEvento = sottoTipoEvento;
		this.identificativoFruitore = identificativoFruitore;
		this.identificativoErogatore = identificativoErogatore;
		this.identificativoStazioneIntermediarioPa = identificativoStazioneIntermediarioPa;
		this.canalePagamento = canalePagamento;
		this.parametriSpecificiInterfaccia = parametriSpecificiInterfaccia;
		this.esito = esito;
	}

	public Long getMygovGiornaleId() {
		return this.mygovGiornaleId;
	}

	public void setMygovGiornaleId(Long mygovGiornaleId) {
		this.mygovGiornaleId = mygovGiornaleId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public Date getDataOraEvento() {
		return this.dataOraEvento;
	}

	public void setDataOraEvento(Date dataOraEvento) {
		this.dataOraEvento = dataOraEvento;
	}

	public String getIdentificativoDominio() {
		return this.identificativoDominio;
	}

	public void setIdentificativoDominio(String identificativoDominio) {
		this.identificativoDominio = identificativoDominio;
	}

	public String getIdentificativoUnivocoVersamento() {
		return this.identificativoUnivocoVersamento;
	}

	public void setIdentificativoUnivocoVersamento(String identificativoUnivocoVersamento) {
		this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
	}

	public String getCodiceContestoPagamento() {
		return this.codiceContestoPagamento;
	}

	public void setCodiceContestoPagamento(String codiceContestoPagamento) {
		this.codiceContestoPagamento = codiceContestoPagamento;
	}

	public String getIdentificativoPrestatoreServiziPagamento() {
		return this.identificativoPrestatoreServiziPagamento;
	}

	public void setIdentificativoPrestatoreServiziPagamento(String identificativoPrestatoreServiziPagamento) {
		this.identificativoPrestatoreServiziPagamento = identificativoPrestatoreServiziPagamento;
	}

	public String getTipoVersamento() {
		return this.tipoVersamento;
	}

	public void setTipoVersamento(String tipoVersamento) {
		this.tipoVersamento = tipoVersamento;
	}

	public String getComponente() {
		return this.componente;
	}

	public void setComponente(String componente) {
		this.componente = componente;
	}

	public String getCategoriaEvento() {
		return this.categoriaEvento;
	}

	public void setCategoriaEvento(String categoriaEvento) {
		this.categoriaEvento = categoriaEvento;
	}

	public String getTipoEvento() {
		return this.tipoEvento;
	}

	public void setTipoEvento(String tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

	public String getSottoTipoEvento() {
		return this.sottoTipoEvento;
	}

	public void setSottoTipoEvento(String sottoTipoEvento) {
		this.sottoTipoEvento = sottoTipoEvento;
	}

	public String getIdentificativoFruitore() {
		return this.identificativoFruitore;
	}

	public void setIdentificativoFruitore(String identificativoFruitore) {
		this.identificativoFruitore = identificativoFruitore;
	}

	public String getIdentificativoErogatore() {
		return this.identificativoErogatore;
	}

	public void setIdentificativoErogatore(String identificativoErogatore) {
		this.identificativoErogatore = identificativoErogatore;
	}

	public String getIdentificativoStazioneIntermediarioPa() {
		return this.identificativoStazioneIntermediarioPa;
	}

	public void setIdentificativoStazioneIntermediarioPa(String identificativoStazioneIntermediarioPa) {
		this.identificativoStazioneIntermediarioPa = identificativoStazioneIntermediarioPa;
	}

	public String getCanalePagamento() {
		return this.canalePagamento;
	}

	public void setCanalePagamento(String canalePagamento) {
		this.canalePagamento = canalePagamento;
	}

	public String getParametriSpecificiInterfaccia() {
		return this.parametriSpecificiInterfaccia;
	}

	public void setParametriSpecificiInterfaccia(String parametriSpecificiInterfaccia) {
		this.parametriSpecificiInterfaccia = parametriSpecificiInterfaccia;
	}

	public String getEsito() {
		return this.esito;
	}

	public void setEsito(String esito) {
		this.esito = esito;
	}

}
