package it.regioneveneto.mygov.payment.nodoregionalefesp.domain;
// Generated Jul 14, 2017 12:18:12 PM by Hibernate Tools 3.5.0.Final

/**
 * MygovProgressiviversamento generated by hbm2java
 */
public class MygovProgressiviversamento implements java.io.Serializable {

	private Long id;

	private int version;

	private String codIpaEnte;

	private String tipoGeneratore;

	private String tipoVersamento;

	private long progressivoVersamento;

	public MygovProgressiviversamento() {
	}

	public MygovProgressiviversamento(String codIpaEnte, String tipoGeneratore, String tipoVersamento, long progressivoVersamento) {
		this.codIpaEnte = codIpaEnte;
		this.tipoGeneratore = tipoGeneratore;
		this.tipoVersamento = tipoVersamento;
		this.progressivoVersamento = progressivoVersamento;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getCodIpaEnte() {
		return this.codIpaEnte;
	}

	public void setCodIpaEnte(String codIpaEnte) {
		this.codIpaEnte = codIpaEnte;
	}

	public String getTipoGeneratore() {
		return this.tipoGeneratore;
	}

	public void setTipoGeneratore(String tipoGeneratore) {
		this.tipoGeneratore = tipoGeneratore;
	}

	public String getTipoVersamento() {
		return this.tipoVersamento;
	}

	public void setTipoVersamento(String tipoVersamento) {
		this.tipoVersamento = tipoVersamento;
	}

	public long getProgressivoVersamento() {
		return this.progressivoVersamento;
	}

	public void setProgressivoVersamento(long progressivoVersamento) {
		this.progressivoVersamento = progressivoVersamento;
	}

}
