package it.regioneveneto.mygov.payment.nodoregionalefesp.domain;
// Generated 18-mar-2019 11.25.47 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * MygovRrErDettaglio generated by hbm2java
 */
public class MygovRrErDettaglio  implements java.io.Serializable {


     private Long mygovRrErDettaglioId;
     private int version;
     private MygovRrEr mygov_rr_er;
     private BigDecimal numRrDatiSingRevSingoloImportoRevocato;
     private String codRrDatiSingRevIdUnivocoRiscossione;
     private String deRrDatiSingRevCausaleRevoca;
     private String deRrDatiSingRevDatiAggiuntiviRevoca;
     private BigDecimal numErDatiSingRevSingoloImportoRevocato;
     private String codErDatiSingRevIdUnivocoRiscossione;
     private String deErDatiSingRevCausaleRevoca;
     private String deErDatiSingRevDatiAggiuntiviRevoca;
     private Date dtCreazione;
     private Date dtUltimaModifica;

    public MygovRrErDettaglio() {
    }

	
    public MygovRrErDettaglio(MygovRrEr mygov_rr_er, BigDecimal numRrDatiSingRevSingoloImportoRevocato, String codRrDatiSingRevIdUnivocoRiscossione, String deRrDatiSingRevCausaleRevoca, String deRrDatiSingRevDatiAggiuntiviRevoca, Date dtCreazione, Date dtUltimaModifica) {
        this.mygov_rr_er = mygov_rr_er;
        this.numRrDatiSingRevSingoloImportoRevocato = numRrDatiSingRevSingoloImportoRevocato;
        this.codRrDatiSingRevIdUnivocoRiscossione = codRrDatiSingRevIdUnivocoRiscossione;
        this.deRrDatiSingRevCausaleRevoca = deRrDatiSingRevCausaleRevoca;
        this.deRrDatiSingRevDatiAggiuntiviRevoca = deRrDatiSingRevDatiAggiuntiviRevoca;
        this.dtCreazione = dtCreazione;
        this.dtUltimaModifica = dtUltimaModifica;
    }
    public MygovRrErDettaglio(MygovRrEr mygov_rr_er, BigDecimal numRrDatiSingRevSingoloImportoRevocato, String codRrDatiSingRevIdUnivocoRiscossione, String deRrDatiSingRevCausaleRevoca, String deRrDatiSingRevDatiAggiuntiviRevoca, BigDecimal numErDatiSingRevSingoloImportoRevocato, String codErDatiSingRevIdUnivocoRiscossione, String deErDatiSingRevCausaleRevoca, String deErDatiSingRevDatiAggiuntiviRevoca, Date dtCreazione, Date dtUltimaModifica) {
       this.mygov_rr_er = mygov_rr_er;
       this.numRrDatiSingRevSingoloImportoRevocato = numRrDatiSingRevSingoloImportoRevocato;
       this.codRrDatiSingRevIdUnivocoRiscossione = codRrDatiSingRevIdUnivocoRiscossione;
       this.deRrDatiSingRevCausaleRevoca = deRrDatiSingRevCausaleRevoca;
       this.deRrDatiSingRevDatiAggiuntiviRevoca = deRrDatiSingRevDatiAggiuntiviRevoca;
       this.numErDatiSingRevSingoloImportoRevocato = numErDatiSingRevSingoloImportoRevocato;
       this.codErDatiSingRevIdUnivocoRiscossione = codErDatiSingRevIdUnivocoRiscossione;
       this.deErDatiSingRevCausaleRevoca = deErDatiSingRevCausaleRevoca;
       this.deErDatiSingRevDatiAggiuntiviRevoca = deErDatiSingRevDatiAggiuntiviRevoca;
       this.dtCreazione = dtCreazione;
       this.dtUltimaModifica = dtUltimaModifica;
    }
   
    public Long getMygovRrErDettaglioId() {
        return this.mygovRrErDettaglioId;
    }
    
    public void setMygovRrErDettaglioId(Long mygovRrErDettaglioId) {
        this.mygovRrErDettaglioId = mygovRrErDettaglioId;
    }
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    public MygovRrEr getMygov_rr_er() {
        return this.mygov_rr_er;
    }
    
    public void setMygov_rr_er(MygovRrEr mygov_rr_er) {
        this.mygov_rr_er = mygov_rr_er;
    }
    public BigDecimal getNumRrDatiSingRevSingoloImportoRevocato() {
        return this.numRrDatiSingRevSingoloImportoRevocato;
    }
    
    public void setNumRrDatiSingRevSingoloImportoRevocato(BigDecimal numRrDatiSingRevSingoloImportoRevocato) {
        this.numRrDatiSingRevSingoloImportoRevocato = numRrDatiSingRevSingoloImportoRevocato;
    }
    public String getCodRrDatiSingRevIdUnivocoRiscossione() {
        return this.codRrDatiSingRevIdUnivocoRiscossione;
    }
    
    public void setCodRrDatiSingRevIdUnivocoRiscossione(String codRrDatiSingRevIdUnivocoRiscossione) {
        this.codRrDatiSingRevIdUnivocoRiscossione = codRrDatiSingRevIdUnivocoRiscossione;
    }
    public String getDeRrDatiSingRevCausaleRevoca() {
        return this.deRrDatiSingRevCausaleRevoca;
    }
    
    public void setDeRrDatiSingRevCausaleRevoca(String deRrDatiSingRevCausaleRevoca) {
        this.deRrDatiSingRevCausaleRevoca = deRrDatiSingRevCausaleRevoca;
    }
    public String getDeRrDatiSingRevDatiAggiuntiviRevoca() {
        return this.deRrDatiSingRevDatiAggiuntiviRevoca;
    }
    
    public void setDeRrDatiSingRevDatiAggiuntiviRevoca(String deRrDatiSingRevDatiAggiuntiviRevoca) {
        this.deRrDatiSingRevDatiAggiuntiviRevoca = deRrDatiSingRevDatiAggiuntiviRevoca;
    }
    public BigDecimal getNumErDatiSingRevSingoloImportoRevocato() {
        return this.numErDatiSingRevSingoloImportoRevocato;
    }
    
    public void setNumErDatiSingRevSingoloImportoRevocato(BigDecimal numErDatiSingRevSingoloImportoRevocato) {
        this.numErDatiSingRevSingoloImportoRevocato = numErDatiSingRevSingoloImportoRevocato;
    }
    public String getCodErDatiSingRevIdUnivocoRiscossione() {
        return this.codErDatiSingRevIdUnivocoRiscossione;
    }
    
    public void setCodErDatiSingRevIdUnivocoRiscossione(String codErDatiSingRevIdUnivocoRiscossione) {
        this.codErDatiSingRevIdUnivocoRiscossione = codErDatiSingRevIdUnivocoRiscossione;
    }
    public String getDeErDatiSingRevCausaleRevoca() {
        return this.deErDatiSingRevCausaleRevoca;
    }
    
    public void setDeErDatiSingRevCausaleRevoca(String deErDatiSingRevCausaleRevoca) {
        this.deErDatiSingRevCausaleRevoca = deErDatiSingRevCausaleRevoca;
    }
    public String getDeErDatiSingRevDatiAggiuntiviRevoca() {
        return this.deErDatiSingRevDatiAggiuntiviRevoca;
    }
    
    public void setDeErDatiSingRevDatiAggiuntiviRevoca(String deErDatiSingRevDatiAggiuntiviRevoca) {
        this.deErDatiSingRevDatiAggiuntiviRevoca = deErDatiSingRevDatiAggiuntiviRevoca;
    }
    public Date getDtCreazione() {
        return this.dtCreazione;
    }
    
    public void setDtCreazione(Date dtCreazione) {
        this.dtCreazione = dtCreazione;
    }
    public Date getDtUltimaModifica() {
        return this.dtUltimaModifica;
    }
    
    public void setDtUltimaModifica(Date dtUltimaModifica) {
        this.dtUltimaModifica = dtUltimaModifica;
    }




}


