package it.regioneveneto.mygov.payment.nodoregionalefesp.domain;
// Generated Jul 14, 2017 12:18:12 PM by Hibernate Tools 3.5.0.Final

/**
 * MygovTipiversamento generated by hbm2java
 */
public class MygovTipiversamento implements java.io.Serializable {

	private Long id;

	private String tipoVersamento;

	private String iuvCodiceTipoVersamentoId;

	private String descrizione;

	public MygovTipiversamento() {
	}

	public MygovTipiversamento(String tipoVersamento, String iuvCodiceTipoVersamentoId) {
		this.tipoVersamento = tipoVersamento;
		this.iuvCodiceTipoVersamentoId = iuvCodiceTipoVersamentoId;
	}

	public MygovTipiversamento(String tipoVersamento, String iuvCodiceTipoVersamentoId, String descrizione) {
		this.tipoVersamento = tipoVersamento;
		this.iuvCodiceTipoVersamentoId = iuvCodiceTipoVersamentoId;
		this.descrizione = descrizione;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTipoVersamento() {
		return this.tipoVersamento;
	}

	public void setTipoVersamento(String tipoVersamento) {
		this.tipoVersamento = tipoVersamento;
	}

	public String getIuvCodiceTipoVersamentoId() {
		return this.iuvCodiceTipoVersamentoId;
	}

	public void setIuvCodiceTipoVersamentoId(String iuvCodiceTipoVersamentoId) {
		this.iuvCodiceTipoVersamentoId = iuvCodiceTipoVersamentoId;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

}
