package it.regioneveneto.mygov.payment.nodoregionalefesp.domain;
// Generated 6-set-2018 9.47.50 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MygovCarrelloRp generated by hbm2java
 */
public class MygovCarrelloRp  implements java.io.Serializable {


     private Long mygovCarrelloRpId;
     private int version;
     private String codAckCarrelloRp;
     private Date dtCreazione;
     private Date dtUltimaModifica;
     private String idSessionCarrello;
     private String deRpSilinviacarrellorpEsito;
     private Integer codRpSilinviacarrellorpRedirect;
     private String codRpSilinviacarrellorpUrl;
     private String codRpSilinviacarrellorpFaultCode;
     private String deRpSilinviacarrellorpFaultString;
     private String codRpSilinviacarrellorpId;
     private String deRpSilinviacarrellorpDescription;
     private String codiceFiscaleEnte;
     private Integer codRpSilinviacarrellorpSerial;
     private String codRpSilinviacarrellorpOriginalFaultCode;
     private String deRpSilinviacarrellorpOriginalFaultString;
     private String deRpSilinviacarrellorpOriginalFaultDescription;
     private Set mygov_rp_e = new HashSet(0);

    public MygovCarrelloRp() {
    }

	
    public MygovCarrelloRp(Date dtCreazione) {
        this.dtCreazione = dtCreazione;
    }
    public MygovCarrelloRp(String codAckCarrelloRp, Date dtCreazione, Date dtUltimaModifica, String idSessionCarrello, String deRpSilinviacarrellorpEsito, Integer codRpSilinviacarrellorpRedirect, String codRpSilinviacarrellorpUrl, String codRpSilinviacarrellorpFaultCode, String deRpSilinviacarrellorpFaultString, String codRpSilinviacarrellorpId, String deRpSilinviacarrellorpDescription, Integer codRpSilinviacarrellorpSerial, Set mygov_rp_e, String codRpSilinviacarrellorpOriginalFaultCode, String deRpSilinviacarrellorpOriginalFaultString, String deRpSilinviacarrellorpOriginalFaultDescription) {
       this.codAckCarrelloRp = codAckCarrelloRp;
       this.dtCreazione = dtCreazione;
       this.dtUltimaModifica = dtUltimaModifica;
       this.idSessionCarrello = idSessionCarrello;
       this.deRpSilinviacarrellorpEsito = deRpSilinviacarrellorpEsito;
       this.codRpSilinviacarrellorpRedirect = codRpSilinviacarrellorpRedirect;
       this.codRpSilinviacarrellorpUrl = codRpSilinviacarrellorpUrl;
       this.codRpSilinviacarrellorpFaultCode = codRpSilinviacarrellorpFaultCode;
       this.deRpSilinviacarrellorpFaultString = deRpSilinviacarrellorpFaultString;
       this.codRpSilinviacarrellorpId = codRpSilinviacarrellorpId;
       this.deRpSilinviacarrellorpDescription = deRpSilinviacarrellorpDescription;
       this.codRpSilinviacarrellorpSerial = codRpSilinviacarrellorpSerial;
       this.mygov_rp_e = mygov_rp_e;
       this.codRpSilinviacarrellorpOriginalFaultCode = codRpSilinviacarrellorpOriginalFaultCode;
       this.deRpSilinviacarrellorpOriginalFaultString = deRpSilinviacarrellorpOriginalFaultString;
       this.deRpSilinviacarrellorpOriginalFaultDescription = deRpSilinviacarrellorpOriginalFaultDescription;
    }
   
    public Long getMygovCarrelloRpId() {
        return this.mygovCarrelloRpId;
    }
    
    public void setMygovCarrelloRpId(Long mygovCarrelloRpId) {
        this.mygovCarrelloRpId = mygovCarrelloRpId;
    }
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    public String getCodAckCarrelloRp() {
        return this.codAckCarrelloRp;
    }
    
    public void setCodAckCarrelloRp(String codAckCarrelloRp) {
        this.codAckCarrelloRp = codAckCarrelloRp;
    }
    public Date getDtCreazione() {
        return this.dtCreazione;
    }
    
    public void setDtCreazione(Date dtCreazione) {
        this.dtCreazione = dtCreazione;
    }
    public Date getDtUltimaModifica() {
        return this.dtUltimaModifica;
    }
    
    public void setDtUltimaModifica(Date dtUltimaModifica) {
        this.dtUltimaModifica = dtUltimaModifica;
    }
    public String getIdSessionCarrello() {
        return this.idSessionCarrello;
    }
    
    public void setIdSessionCarrello(String idSessionCarrello) {
        this.idSessionCarrello = idSessionCarrello;
    }
    public String getDeRpSilinviacarrellorpEsito() {
        return this.deRpSilinviacarrellorpEsito;
    }
    
    public void setDeRpSilinviacarrellorpEsito(String deRpSilinviacarrellorpEsito) {
        this.deRpSilinviacarrellorpEsito = deRpSilinviacarrellorpEsito;
    }
    public Integer getCodRpSilinviacarrellorpRedirect() {
        return this.codRpSilinviacarrellorpRedirect;
    }
    
    public void setCodRpSilinviacarrellorpRedirect(Integer codRpSilinviacarrellorpRedirect) {
        this.codRpSilinviacarrellorpRedirect = codRpSilinviacarrellorpRedirect;
    }
    public String getCodRpSilinviacarrellorpUrl() {
        return this.codRpSilinviacarrellorpUrl;
    }
    
    public void setCodRpSilinviacarrellorpUrl(String codRpSilinviacarrellorpUrl) {
        this.codRpSilinviacarrellorpUrl = codRpSilinviacarrellorpUrl;
    }
    public String getCodRpSilinviacarrellorpFaultCode() {
        return this.codRpSilinviacarrellorpFaultCode;
    }
    
    public void setCodRpSilinviacarrellorpFaultCode(String codRpSilinviacarrellorpFaultCode) {
        this.codRpSilinviacarrellorpFaultCode = codRpSilinviacarrellorpFaultCode;
    }
    public String getDeRpSilinviacarrellorpFaultString() {
        return this.deRpSilinviacarrellorpFaultString;
    }
    
    public void setDeRpSilinviacarrellorpFaultString(String deRpSilinviacarrellorpFaultString) {
        this.deRpSilinviacarrellorpFaultString = deRpSilinviacarrellorpFaultString;
    }
    public String getCodRpSilinviacarrellorpId() {
        return this.codRpSilinviacarrellorpId;
    }
    
    public void setCodRpSilinviacarrellorpId(String codRpSilinviacarrellorpId) {
        this.codRpSilinviacarrellorpId = codRpSilinviacarrellorpId;
    }
    public String getDeRpSilinviacarrellorpDescription() {
        return this.deRpSilinviacarrellorpDescription;
    }
    
    public void setDeRpSilinviacarrellorpDescription(String deRpSilinviacarrellorpDescription) {
        this.deRpSilinviacarrellorpDescription = deRpSilinviacarrellorpDescription;
    }
    public Integer getCodRpSilinviacarrellorpSerial() {
        return this.codRpSilinviacarrellorpSerial;
    }
    
    public void setCodRpSilinviacarrellorpSerial(Integer codRpSilinviacarrellorpSerial) {
        this.codRpSilinviacarrellorpSerial = codRpSilinviacarrellorpSerial;
    }
    public Set getMygov_rp_e() {
        return this.mygov_rp_e;
    }
    
    public void setMygov_rp_e(Set mygov_rp_e) {
        this.mygov_rp_e = mygov_rp_e;
    }


	public String getCodiceFiscaleEnte() {
		return codiceFiscaleEnte;
	}


	public void setCodiceFiscaleEnte(String codiceFiscaleEnte) {
		this.codiceFiscaleEnte = codiceFiscaleEnte;
	}


	public String getCodRpSilinviacarrellorpOriginalFaultCode() {
		return codRpSilinviacarrellorpOriginalFaultCode;
	}


	public void setCodRpSilinviacarrellorpOriginalFaultCode(String codRpSilinviacarrellorpOriginalFaultCode) {
		this.codRpSilinviacarrellorpOriginalFaultCode = codRpSilinviacarrellorpOriginalFaultCode;
	}


	public String getDeRpSilinviacarrellorpOriginalFaultString() {
		return deRpSilinviacarrellorpOriginalFaultString;
	}


	public void setDeRpSilinviacarrellorpOriginalFaultString(String deRpSilinviacarrellorpOriginalFaultString) {
		this.deRpSilinviacarrellorpOriginalFaultString = deRpSilinviacarrellorpOriginalFaultString;
	}


	public String getDeRpSilinviacarrellorpOriginalFaultDescription() {
		return deRpSilinviacarrellorpOriginalFaultDescription;
	}


	public void setDeRpSilinviacarrellorpOriginalFaultDescription(String deRpSilinviacarrellorpOriginalFaultDescription) {
		this.deRpSilinviacarrellorpOriginalFaultDescription = deRpSilinviacarrellorpOriginalFaultDescription;
	}




}


