package it.regioneveneto.mygov.payment.nodoregionalefesp.domain;
// Generated 6-set-2018 10.42.21 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MygovCarrelloRpt generated by hbm2java
 */
public class MygovCarrelloRpt  implements java.io.Serializable {


     private Long mygovCarrelloRptId;
     private int version;
     private String codAckCarrelloRpt;
     private Long mygovCarrelloRpId;
     private Date dtCreazione;
     private Date dtUltimaModifica;
     private String codRptInviacarrellorptIdCarrello;
     private String codRptInviacarrellorptIdIntermediarioPa;
     private String codRptInviacarrellorptIdStazioneIntermediarioPa;
     private String deRptInviacarrellorptPassword;
     private String codRptInviacarrellorptIdPsp;
     private String codRptInviacarrellorptIdIntermediarioPsp;
     private String codRptInviacarrellorptIdCanale;
     private String deRptInviacarrellorptEsitoComplessivoOperazione;
     private String codRptInviacarrellorptUrl;
     private String codRptInviacarrellorptFaultCode;
     private String codRptInviacarrellorptFaultString;
     private String codRptInviacarrellorptId;
     private String deRptInviacarrellorptDescription;
     private Integer numRptInviacarrellorptSerial;
     private String codRptSilinviacarrellorptOriginalFaultCode;
     private String deRptSilinviacarrellorptOriginalFaultString;
     private String deRptSilinviacarrellorptOriginalFaultDescription;
     private Set mygov_rpt_rt = new HashSet(0);

    public MygovCarrelloRpt() {
    }

	
    public MygovCarrelloRpt(Date dtCreazione) {
        this.dtCreazione = dtCreazione;
    }
    public MygovCarrelloRpt(String codAckCarrelloRpt, Long mygovCarrelloRpId, Date dtCreazione, Date dtUltimaModifica, String codRptInviacarrellorptIdCarrello, String codRptInviacarrellorptIdIntermediarioPa, String codRptInviacarrellorptIdStazioneIntermediarioPa, String deRptInviacarrellorptPassword, String codRptInviacarrellorptIdPsp, String codRptInviacarrellorptIdIntermediarioPsp, String codRptInviacarrellorptIdCanale, String deRptInviacarrellorptEsitoComplessivoOperazione, String codRptInviacarrellorptUrl, String codRptInviacarrellorptFaultCode, String codRptInviacarrellorptFaultString, String codRptInviacarrellorptId, String deRptInviacarrellorptDescription, Integer numRptInviacarrellorptSerial, Set mygov_rpt_rt, String codRptSilinviacarrellorptOriginalFaultCode, String deRptSilinviacarrellorptOriginalFaultString, String deRptSilinviacarrellorptOriginalFaultDescription) {
       this.codAckCarrelloRpt = codAckCarrelloRpt;
       this.mygovCarrelloRpId = mygovCarrelloRpId;
       this.dtCreazione = dtCreazione;
       this.dtUltimaModifica = dtUltimaModifica;
       this.codRptInviacarrellorptIdCarrello = codRptInviacarrellorptIdCarrello;
       this.codRptInviacarrellorptIdIntermediarioPa = codRptInviacarrellorptIdIntermediarioPa;
       this.codRptInviacarrellorptIdStazioneIntermediarioPa = codRptInviacarrellorptIdStazioneIntermediarioPa;
       this.deRptInviacarrellorptPassword = deRptInviacarrellorptPassword;
       this.codRptInviacarrellorptIdPsp = codRptInviacarrellorptIdPsp;
       this.codRptInviacarrellorptIdIntermediarioPsp = codRptInviacarrellorptIdIntermediarioPsp;
       this.codRptInviacarrellorptIdCanale = codRptInviacarrellorptIdCanale;
       this.deRptInviacarrellorptEsitoComplessivoOperazione = deRptInviacarrellorptEsitoComplessivoOperazione;
       this.codRptInviacarrellorptUrl = codRptInviacarrellorptUrl;
       this.codRptInviacarrellorptFaultCode = codRptInviacarrellorptFaultCode;
       this.codRptInviacarrellorptFaultString = codRptInviacarrellorptFaultString;
       this.codRptInviacarrellorptId = codRptInviacarrellorptId;
       this.deRptInviacarrellorptDescription = deRptInviacarrellorptDescription;
       this.numRptInviacarrellorptSerial = numRptInviacarrellorptSerial;
       this.mygov_rpt_rt = mygov_rpt_rt;
       this.codRptSilinviacarrellorptOriginalFaultCode = codRptSilinviacarrellorptOriginalFaultCode;
       this.deRptSilinviacarrellorptOriginalFaultString = deRptSilinviacarrellorptOriginalFaultString;
       this.deRptSilinviacarrellorptOriginalFaultDescription = deRptSilinviacarrellorptOriginalFaultDescription;
    }
   
    public Long getMygovCarrelloRptId() {
        return this.mygovCarrelloRptId;
    }
    
    public void setMygovCarrelloRptId(Long mygovCarrelloRptId) {
        this.mygovCarrelloRptId = mygovCarrelloRptId;
    }
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    public String getCodAckCarrelloRpt() {
        return this.codAckCarrelloRpt;
    }
    
    public void setCodAckCarrelloRpt(String codAckCarrelloRpt) {
        this.codAckCarrelloRpt = codAckCarrelloRpt;
    }
    public Long getMygovCarrelloRpId() {
        return this.mygovCarrelloRpId;
    }
    
    public void setMygovCarrelloRpId(Long mygovCarrelloRpId) {
        this.mygovCarrelloRpId = mygovCarrelloRpId;
    }
    public Date getDtCreazione() {
        return this.dtCreazione;
    }
    
    public void setDtCreazione(Date dtCreazione) {
        this.dtCreazione = dtCreazione;
    }
    public Date getDtUltimaModifica() {
        return this.dtUltimaModifica;
    }
    
    public void setDtUltimaModifica(Date dtUltimaModifica) {
        this.dtUltimaModifica = dtUltimaModifica;
    }
    public String getCodRptInviacarrellorptIdCarrello() {
        return this.codRptInviacarrellorptIdCarrello;
    }
    
    public void setCodRptInviacarrellorptIdCarrello(String codRptInviacarrellorptIdCarrello) {
        this.codRptInviacarrellorptIdCarrello = codRptInviacarrellorptIdCarrello;
    }
    public String getCodRptInviacarrellorptIdIntermediarioPa() {
        return this.codRptInviacarrellorptIdIntermediarioPa;
    }
    
    public void setCodRptInviacarrellorptIdIntermediarioPa(String codRptInviacarrellorptIdIntermediarioPa) {
        this.codRptInviacarrellorptIdIntermediarioPa = codRptInviacarrellorptIdIntermediarioPa;
    }
    public String getCodRptInviacarrellorptIdStazioneIntermediarioPa() {
        return this.codRptInviacarrellorptIdStazioneIntermediarioPa;
    }
    
    public void setCodRptInviacarrellorptIdStazioneIntermediarioPa(String codRptInviacarrellorptIdStazioneIntermediarioPa) {
        this.codRptInviacarrellorptIdStazioneIntermediarioPa = codRptInviacarrellorptIdStazioneIntermediarioPa;
    }
    public String getDeRptInviacarrellorptPassword() {
        return this.deRptInviacarrellorptPassword;
    }
    
    public void setDeRptInviacarrellorptPassword(String deRptInviacarrellorptPassword) {
        this.deRptInviacarrellorptPassword = deRptInviacarrellorptPassword;
    }
    public String getCodRptInviacarrellorptIdPsp() {
        return this.codRptInviacarrellorptIdPsp;
    }
    
    public void setCodRptInviacarrellorptIdPsp(String codRptInviacarrellorptIdPsp) {
        this.codRptInviacarrellorptIdPsp = codRptInviacarrellorptIdPsp;
    }
    public String getCodRptInviacarrellorptIdIntermediarioPsp() {
        return this.codRptInviacarrellorptIdIntermediarioPsp;
    }
    
    public void setCodRptInviacarrellorptIdIntermediarioPsp(String codRptInviacarrellorptIdIntermediarioPsp) {
        this.codRptInviacarrellorptIdIntermediarioPsp = codRptInviacarrellorptIdIntermediarioPsp;
    }
    public String getCodRptInviacarrellorptIdCanale() {
        return this.codRptInviacarrellorptIdCanale;
    }
    
    public void setCodRptInviacarrellorptIdCanale(String codRptInviacarrellorptIdCanale) {
        this.codRptInviacarrellorptIdCanale = codRptInviacarrellorptIdCanale;
    }
    public String getDeRptInviacarrellorptEsitoComplessivoOperazione() {
        return this.deRptInviacarrellorptEsitoComplessivoOperazione;
    }
    
    public void setDeRptInviacarrellorptEsitoComplessivoOperazione(String deRptInviacarrellorptEsitoComplessivoOperazione) {
        this.deRptInviacarrellorptEsitoComplessivoOperazione = deRptInviacarrellorptEsitoComplessivoOperazione;
    }
    public String getCodRptInviacarrellorptUrl() {
        return this.codRptInviacarrellorptUrl;
    }
    
    public void setCodRptInviacarrellorptUrl(String codRptInviacarrellorptUrl) {
        this.codRptInviacarrellorptUrl = codRptInviacarrellorptUrl;
    }
    public String getCodRptInviacarrellorptFaultCode() {
        return this.codRptInviacarrellorptFaultCode;
    }
    
    public void setCodRptInviacarrellorptFaultCode(String codRptInviacarrellorptFaultCode) {
        this.codRptInviacarrellorptFaultCode = codRptInviacarrellorptFaultCode;
    }
    public String getCodRptInviacarrellorptFaultString() {
        return this.codRptInviacarrellorptFaultString;
    }
    
    public void setCodRptInviacarrellorptFaultString(String codRptInviacarrellorptFaultString) {
        this.codRptInviacarrellorptFaultString = codRptInviacarrellorptFaultString;
    }
    public String getCodRptInviacarrellorptId() {
        return this.codRptInviacarrellorptId;
    }
    
    public void setCodRptInviacarrellorptId(String codRptInviacarrellorptId) {
        this.codRptInviacarrellorptId = codRptInviacarrellorptId;
    }
    public String getDeRptInviacarrellorptDescription() {
        return this.deRptInviacarrellorptDescription;
    }
    
    public void setDeRptInviacarrellorptDescription(String deRptInviacarrellorptDescription) {
        this.deRptInviacarrellorptDescription = deRptInviacarrellorptDescription;
    }
    public Integer getNumRptInviacarrellorptSerial() {
        return this.numRptInviacarrellorptSerial;
    }
    
    public void setNumRptInviacarrellorptSerial(Integer numRptInviacarrellorptSerial) {
        this.numRptInviacarrellorptSerial = numRptInviacarrellorptSerial;
    }
    public Set getMygov_rpt_rt() {
        return this.mygov_rpt_rt;
    }
    
    public void setMygov_rpt_rt(Set mygov_rpt_rt) {
        this.mygov_rpt_rt = mygov_rpt_rt;
    }


	public String getCodRptSilinviacarrellorptOriginalFaultCode() {
		return codRptSilinviacarrellorptOriginalFaultCode;
	}


	public void setCodRptSilinviacarrellorptOriginalFaultCode(String codRptSilinviacarrellorptOriginalFaultCode) {
		this.codRptSilinviacarrellorptOriginalFaultCode = codRptSilinviacarrellorptOriginalFaultCode;
	}


	public String getDeRptSilinviacarrellorptOriginalFaultString() {
		return deRptSilinviacarrellorptOriginalFaultString;
	}


	public void setDeRptSilinviacarrellorptOriginalFaultString(String deRptSilinviacarrellorptOriginalFaultString) {
		this.deRptSilinviacarrellorptOriginalFaultString = deRptSilinviacarrellorptOriginalFaultString;
	}


	public String getDeRptSilinviacarrellorptOriginalFaultDescription() {
		return deRptSilinviacarrellorptOriginalFaultDescription;
	}


	public void setDeRptSilinviacarrellorptOriginalFaultDescription(
			String deRptSilinviacarrellorptOriginalFaultDescription) {
		this.deRptSilinviacarrellorptOriginalFaultDescription = deRptSilinviacarrellorptOriginalFaultDescription;
	}




}


