package it.regioneveneto.mygov.payment.nodoregionalefesp.domain;
// Generated Jul 14, 2017 12:18:12 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * MygovRptRtDettaglio generated by hbm2java
 */
public class MygovRptRtDettaglio implements java.io.Serializable {

	private Long mygovRptRtDettaglioId;

	private int version;

	private MygovRptRt mygov_rpt_rt;

	private Date dtCreazione;

	private Date dtUltimaModifica;

	private BigDecimal numRptDatiVersDatiSingVersImportoSingoloVersamento;

	private BigDecimal numRptDatiVersDatiSingVersCommissioneCaricoPa;

	private String deRptDatiVersDatiSingVersIbanAccredito;

	private String deRptDatiVersDatiSingVersBicAccredito;

	private String deRptDatiVersDatiSingVersIbanAppoggio;

	private String deRptDatiVersDatiSingVersBicAppoggio;

	private String codRptDatiVersDatiSingVersCredenzialiPagatore;

	private String deRptDatiVersDatiSingVersCausaleVersamento;

	private String deRptDatiVersDatiSingVersDatiSpecificiRiscossione;

	private BigDecimal numRtDatiPagDatiSingPagSingoloImportoPagato;

	private String deRtDatiPagDatiSingPagEsitoSingoloPagamento;

	private Date dtRtDatiPagDatiSingPagDataEsitoSingoloPagamento;

	private String codRtDatiPagDatiSingPagIdUnivocoRiscossione;

	private String deRtDatiPagDatiSingPagCausaleVersamento;

	private String deRtDatiPagDatiSingPagDatiSpecificiRiscossione;

	private BigDecimal numRtDatiPagDatiSingPagCommissioniApplicatePsp;

	private String codRtDatiPagDatiSingPagAllegatoRicevutaTipo;

	private byte[] blbRtDatiPagDatiSingPagAllegatoRicevutaTest;

	private String codRptDatiVersDatiSingVersDatiMbdTipoBollo;

	private String codRptDatiVersDatiSingVersDatiMbdHashDocumento;

	private String codRptDatiVersDatiSingVersDatiMbdProvinciaResidenza;

	public MygovRptRtDettaglio() {
	}

	public MygovRptRtDettaglio(MygovRptRt mygov_rpt_rt, Date dtCreazione, Date dtUltimaModifica, BigDecimal numRptDatiVersDatiSingVersImportoSingoloVersamento,
			String deRptDatiVersDatiSingVersCausaleVersamento, String deRptDatiVersDatiSingVersDatiSpecificiRiscossione) {
		this.mygov_rpt_rt = mygov_rpt_rt;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.numRptDatiVersDatiSingVersImportoSingoloVersamento = numRptDatiVersDatiSingVersImportoSingoloVersamento;
		this.deRptDatiVersDatiSingVersCausaleVersamento = deRptDatiVersDatiSingVersCausaleVersamento;
		this.deRptDatiVersDatiSingVersDatiSpecificiRiscossione = deRptDatiVersDatiSingVersDatiSpecificiRiscossione;
	}

	public MygovRptRtDettaglio(MygovRptRt mygov_rpt_rt, Date dtCreazione, Date dtUltimaModifica, BigDecimal numRptDatiVersDatiSingVersImportoSingoloVersamento,
			BigDecimal numRptDatiVersDatiSingVersCommissioneCaricoPa, String deRptDatiVersDatiSingVersIbanAccredito,
			String deRptDatiVersDatiSingVersBicAccredito, String deRptDatiVersDatiSingVersIbanAppoggio, String deRptDatiVersDatiSingVersBicAppoggio,
			String codRptDatiVersDatiSingVersCredenzialiPagatore, String deRptDatiVersDatiSingVersCausaleVersamento,
			String deRptDatiVersDatiSingVersDatiSpecificiRiscossione, BigDecimal numRtDatiPagDatiSingPagSingoloImportoPagato,
			String deRtDatiPagDatiSingPagEsitoSingoloPagamento, Date dtRtDatiPagDatiSingPagDataEsitoSingoloPagamento,
			String codRtDatiPagDatiSingPagIdUnivocoRiscossione, String deRtDatiPagDatiSingPagCausaleVersamento,
			String deRtDatiPagDatiSingPagDatiSpecificiRiscossione, BigDecimal numRtDatiPagDatiSingPagCommissioniApplicatePsp,
			String codRtDatiPagDatiSingPagAllegatoRicevutaTipo, byte[] blbRtDatiPagDatiSingPagAllegatoRicevutaTest,
			String codRptDatiVersDatiSingVersDatiMbdTipoBollo, String codRptDatiVersDatiSingVersDatiMbdHashDocumento,
			String codRptDatiVersDatiSingVersDatiMbdProvinciaResidenza) {
		this.mygov_rpt_rt = mygov_rpt_rt;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.numRptDatiVersDatiSingVersImportoSingoloVersamento = numRptDatiVersDatiSingVersImportoSingoloVersamento;
		this.numRptDatiVersDatiSingVersCommissioneCaricoPa = numRptDatiVersDatiSingVersCommissioneCaricoPa;
		this.deRptDatiVersDatiSingVersIbanAccredito = deRptDatiVersDatiSingVersIbanAccredito;
		this.deRptDatiVersDatiSingVersBicAccredito = deRptDatiVersDatiSingVersBicAccredito;
		this.deRptDatiVersDatiSingVersIbanAppoggio = deRptDatiVersDatiSingVersIbanAppoggio;
		this.deRptDatiVersDatiSingVersBicAppoggio = deRptDatiVersDatiSingVersBicAppoggio;
		this.codRptDatiVersDatiSingVersCredenzialiPagatore = codRptDatiVersDatiSingVersCredenzialiPagatore;
		this.deRptDatiVersDatiSingVersCausaleVersamento = deRptDatiVersDatiSingVersCausaleVersamento;
		this.deRptDatiVersDatiSingVersDatiSpecificiRiscossione = deRptDatiVersDatiSingVersDatiSpecificiRiscossione;
		this.numRtDatiPagDatiSingPagSingoloImportoPagato = numRtDatiPagDatiSingPagSingoloImportoPagato;
		this.deRtDatiPagDatiSingPagEsitoSingoloPagamento = deRtDatiPagDatiSingPagEsitoSingoloPagamento;
		this.dtRtDatiPagDatiSingPagDataEsitoSingoloPagamento = dtRtDatiPagDatiSingPagDataEsitoSingoloPagamento;
		this.codRtDatiPagDatiSingPagIdUnivocoRiscossione = codRtDatiPagDatiSingPagIdUnivocoRiscossione;
		this.deRtDatiPagDatiSingPagCausaleVersamento = deRtDatiPagDatiSingPagCausaleVersamento;
		this.deRtDatiPagDatiSingPagDatiSpecificiRiscossione = deRtDatiPagDatiSingPagDatiSpecificiRiscossione;
		this.numRtDatiPagDatiSingPagCommissioniApplicatePsp = numRtDatiPagDatiSingPagCommissioniApplicatePsp;
		this.codRtDatiPagDatiSingPagAllegatoRicevutaTipo = codRtDatiPagDatiSingPagAllegatoRicevutaTipo;
		this.blbRtDatiPagDatiSingPagAllegatoRicevutaTest = blbRtDatiPagDatiSingPagAllegatoRicevutaTest;
		this.codRptDatiVersDatiSingVersDatiMbdTipoBollo = codRptDatiVersDatiSingVersDatiMbdTipoBollo;
		this.codRptDatiVersDatiSingVersDatiMbdHashDocumento = codRptDatiVersDatiSingVersDatiMbdHashDocumento;
		this.codRptDatiVersDatiSingVersDatiMbdProvinciaResidenza = codRptDatiVersDatiSingVersDatiMbdProvinciaResidenza;
	}

	public Long getMygovRptRtDettaglioId() {
		return this.mygovRptRtDettaglioId;
	}

	public void setMygovRptRtDettaglioId(Long mygovRptRtDettaglioId) {
		this.mygovRptRtDettaglioId = mygovRptRtDettaglioId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public MygovRptRt getMygov_rpt_rt() {
		return this.mygov_rpt_rt;
	}

	public void setMygov_rpt_rt(MygovRptRt mygov_rpt_rt) {
		this.mygov_rpt_rt = mygov_rpt_rt;
	}

	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

	public BigDecimal getNumRptDatiVersDatiSingVersImportoSingoloVersamento() {
		return this.numRptDatiVersDatiSingVersImportoSingoloVersamento;
	}

	public void setNumRptDatiVersDatiSingVersImportoSingoloVersamento(BigDecimal numRptDatiVersDatiSingVersImportoSingoloVersamento) {
		this.numRptDatiVersDatiSingVersImportoSingoloVersamento = numRptDatiVersDatiSingVersImportoSingoloVersamento;
	}

	public BigDecimal getNumRptDatiVersDatiSingVersCommissioneCaricoPa() {
		return this.numRptDatiVersDatiSingVersCommissioneCaricoPa;
	}

	public void setNumRptDatiVersDatiSingVersCommissioneCaricoPa(BigDecimal numRptDatiVersDatiSingVersCommissioneCaricoPa) {
		this.numRptDatiVersDatiSingVersCommissioneCaricoPa = numRptDatiVersDatiSingVersCommissioneCaricoPa;
	}

	public String getDeRptDatiVersDatiSingVersIbanAccredito() {
		return this.deRptDatiVersDatiSingVersIbanAccredito;
	}

	public void setDeRptDatiVersDatiSingVersIbanAccredito(String deRptDatiVersDatiSingVersIbanAccredito) {
		this.deRptDatiVersDatiSingVersIbanAccredito = deRptDatiVersDatiSingVersIbanAccredito;
	}

	public String getDeRptDatiVersDatiSingVersBicAccredito() {
		return this.deRptDatiVersDatiSingVersBicAccredito;
	}

	public void setDeRptDatiVersDatiSingVersBicAccredito(String deRptDatiVersDatiSingVersBicAccredito) {
		this.deRptDatiVersDatiSingVersBicAccredito = deRptDatiVersDatiSingVersBicAccredito;
	}

	public String getDeRptDatiVersDatiSingVersIbanAppoggio() {
		return this.deRptDatiVersDatiSingVersIbanAppoggio;
	}

	public void setDeRptDatiVersDatiSingVersIbanAppoggio(String deRptDatiVersDatiSingVersIbanAppoggio) {
		this.deRptDatiVersDatiSingVersIbanAppoggio = deRptDatiVersDatiSingVersIbanAppoggio;
	}

	public String getDeRptDatiVersDatiSingVersBicAppoggio() {
		return this.deRptDatiVersDatiSingVersBicAppoggio;
	}

	public void setDeRptDatiVersDatiSingVersBicAppoggio(String deRptDatiVersDatiSingVersBicAppoggio) {
		this.deRptDatiVersDatiSingVersBicAppoggio = deRptDatiVersDatiSingVersBicAppoggio;
	}

	public String getCodRptDatiVersDatiSingVersCredenzialiPagatore() {
		return this.codRptDatiVersDatiSingVersCredenzialiPagatore;
	}

	public void setCodRptDatiVersDatiSingVersCredenzialiPagatore(String codRptDatiVersDatiSingVersCredenzialiPagatore) {
		this.codRptDatiVersDatiSingVersCredenzialiPagatore = codRptDatiVersDatiSingVersCredenzialiPagatore;
	}

	public String getDeRptDatiVersDatiSingVersCausaleVersamento() {
		return this.deRptDatiVersDatiSingVersCausaleVersamento;
	}

	public void setDeRptDatiVersDatiSingVersCausaleVersamento(String deRptDatiVersDatiSingVersCausaleVersamento) {
		this.deRptDatiVersDatiSingVersCausaleVersamento = deRptDatiVersDatiSingVersCausaleVersamento;
	}

	public String getDeRptDatiVersDatiSingVersDatiSpecificiRiscossione() {
		return this.deRptDatiVersDatiSingVersDatiSpecificiRiscossione;
	}

	public void setDeRptDatiVersDatiSingVersDatiSpecificiRiscossione(String deRptDatiVersDatiSingVersDatiSpecificiRiscossione) {
		this.deRptDatiVersDatiSingVersDatiSpecificiRiscossione = deRptDatiVersDatiSingVersDatiSpecificiRiscossione;
	}

	public BigDecimal getNumRtDatiPagDatiSingPagSingoloImportoPagato() {
		return this.numRtDatiPagDatiSingPagSingoloImportoPagato;
	}

	public void setNumRtDatiPagDatiSingPagSingoloImportoPagato(BigDecimal numRtDatiPagDatiSingPagSingoloImportoPagato) {
		this.numRtDatiPagDatiSingPagSingoloImportoPagato = numRtDatiPagDatiSingPagSingoloImportoPagato;
	}

	public String getDeRtDatiPagDatiSingPagEsitoSingoloPagamento() {
		return this.deRtDatiPagDatiSingPagEsitoSingoloPagamento;
	}

	public void setDeRtDatiPagDatiSingPagEsitoSingoloPagamento(String deRtDatiPagDatiSingPagEsitoSingoloPagamento) {
		this.deRtDatiPagDatiSingPagEsitoSingoloPagamento = deRtDatiPagDatiSingPagEsitoSingoloPagamento;
	}

	public Date getDtRtDatiPagDatiSingPagDataEsitoSingoloPagamento() {
		return this.dtRtDatiPagDatiSingPagDataEsitoSingoloPagamento;
	}

	public void setDtRtDatiPagDatiSingPagDataEsitoSingoloPagamento(Date dtRtDatiPagDatiSingPagDataEsitoSingoloPagamento) {
		this.dtRtDatiPagDatiSingPagDataEsitoSingoloPagamento = dtRtDatiPagDatiSingPagDataEsitoSingoloPagamento;
	}

	public String getCodRtDatiPagDatiSingPagIdUnivocoRiscossione() {
		return this.codRtDatiPagDatiSingPagIdUnivocoRiscossione;
	}

	public void setCodRtDatiPagDatiSingPagIdUnivocoRiscossione(String codRtDatiPagDatiSingPagIdUnivocoRiscossione) {
		this.codRtDatiPagDatiSingPagIdUnivocoRiscossione = codRtDatiPagDatiSingPagIdUnivocoRiscossione;
	}

	public String getDeRtDatiPagDatiSingPagCausaleVersamento() {
		return this.deRtDatiPagDatiSingPagCausaleVersamento;
	}

	public void setDeRtDatiPagDatiSingPagCausaleVersamento(String deRtDatiPagDatiSingPagCausaleVersamento) {
		this.deRtDatiPagDatiSingPagCausaleVersamento = deRtDatiPagDatiSingPagCausaleVersamento;
	}

	public String getDeRtDatiPagDatiSingPagDatiSpecificiRiscossione() {
		return this.deRtDatiPagDatiSingPagDatiSpecificiRiscossione;
	}

	public void setDeRtDatiPagDatiSingPagDatiSpecificiRiscossione(String deRtDatiPagDatiSingPagDatiSpecificiRiscossione) {
		this.deRtDatiPagDatiSingPagDatiSpecificiRiscossione = deRtDatiPagDatiSingPagDatiSpecificiRiscossione;
	}

	public BigDecimal getNumRtDatiPagDatiSingPagCommissioniApplicatePsp() {
		return this.numRtDatiPagDatiSingPagCommissioniApplicatePsp;
	}

	public void setNumRtDatiPagDatiSingPagCommissioniApplicatePsp(BigDecimal numRtDatiPagDatiSingPagCommissioniApplicatePsp) {
		this.numRtDatiPagDatiSingPagCommissioniApplicatePsp = numRtDatiPagDatiSingPagCommissioniApplicatePsp;
	}

	public String getCodRtDatiPagDatiSingPagAllegatoRicevutaTipo() {
		return this.codRtDatiPagDatiSingPagAllegatoRicevutaTipo;
	}

	public void setCodRtDatiPagDatiSingPagAllegatoRicevutaTipo(String codRtDatiPagDatiSingPagAllegatoRicevutaTipo) {
		this.codRtDatiPagDatiSingPagAllegatoRicevutaTipo = codRtDatiPagDatiSingPagAllegatoRicevutaTipo;
	}

	public byte[] getBlbRtDatiPagDatiSingPagAllegatoRicevutaTest() {
		return this.blbRtDatiPagDatiSingPagAllegatoRicevutaTest;
	}

	public void setBlbRtDatiPagDatiSingPagAllegatoRicevutaTest(byte[] blbRtDatiPagDatiSingPagAllegatoRicevutaTest) {
		this.blbRtDatiPagDatiSingPagAllegatoRicevutaTest = blbRtDatiPagDatiSingPagAllegatoRicevutaTest;
	}

	public String getCodRptDatiVersDatiSingVersDatiMbdTipoBollo() {
		return this.codRptDatiVersDatiSingVersDatiMbdTipoBollo;
	}

	public void setCodRptDatiVersDatiSingVersDatiMbdTipoBollo(String codRptDatiVersDatiSingVersDatiMbdTipoBollo) {
		this.codRptDatiVersDatiSingVersDatiMbdTipoBollo = codRptDatiVersDatiSingVersDatiMbdTipoBollo;
	}

	public String getCodRptDatiVersDatiSingVersDatiMbdHashDocumento() {
		return this.codRptDatiVersDatiSingVersDatiMbdHashDocumento;
	}

	public void setCodRptDatiVersDatiSingVersDatiMbdHashDocumento(String codRptDatiVersDatiSingVersDatiMbdHashDocumento) {
		this.codRptDatiVersDatiSingVersDatiMbdHashDocumento = codRptDatiVersDatiSingVersDatiMbdHashDocumento;
	}

	public String getCodRptDatiVersDatiSingVersDatiMbdProvinciaResidenza() {
		return this.codRptDatiVersDatiSingVersDatiMbdProvinciaResidenza;
	}

	public void setCodRptDatiVersDatiSingVersDatiMbdProvinciaResidenza(String codRptDatiVersDatiSingVersDatiMbdProvinciaResidenza) {
		this.codRptDatiVersDatiSingVersDatiMbdProvinciaResidenza = codRptDatiVersDatiSingVersDatiMbdProvinciaResidenza;
	}

}
