apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypay4-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: rook-cephfs-external

